server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/api/v1/request/**
        - id: simulation-service
          uri: lb://simulation-service
          predicates:
            - Path=/api/v1/simulation/**
        - id: state-service
          uri: lb://state-service
          predicates:
            - Path=/api/v1/state/**
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/api/v1/evaluation/**
